version: '3.4'

services:
  itemsmicroservice.api:
    image: ${DOCKER_REGISTRY-}itemsmicroserviceapi
    container_name: API
    build:
      context: .
      dockerfile: ItemsMicroservice.Api/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - itemsmicroservice.db
      - itemsmicroservice.redis
      - itemsmicroservice.rabbitmq
  
  itemsmicroservice.db:
    image: postgres:latest
    container_name: Database
    environment:
      - POSTGRES_DB=itemsmicroservice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  itemsmicroservice.redis:
    image: redis:latest
    container_name: Redis
    volumes:
    - ./.containers/redis:/data
    ports:
    - 6379:6379

  itemsmicroservice.rabbitmq:
    image: rabbitmq:management
    container_name: Queue
    hostname: itemsmicroservice-queue
    volumes:
    - ./.containers/queue/data/:/var/lib/rabbitmq
    - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
    - 5672:5672
    - 15672:15672