@apiUrl = https://localhost/api
@bearerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImp0aSI6IjE4MGM3NjBhLTQyYjEtNDg2ZC05NWI0LWZjNDcyMTVjYzZiZCIsImVtYWlsIjoiYWRtaW4iLCJpZCI6IjVjZDcwMjBhLTI4OGUtNDQ5YS05NDQ0LTcwMjY3MmJlZDI0NSIsInJvbGUiOiJJdGVtc0FkbWluIiwibmJmIjoxNjc1ODg5OTkxLCJleHAiOjE2NzY0OTQ3OTEsImlhdCI6MTY3NTg4OTk5MX0.7U3fbVpTaoTSg0qUQHwvli35v6h9H2-nMskKpu-LdRI
@code = test

### Login as "Administracja Items"
POST {{apiUrl}}/login
Content-Type: application/json

{
  "username": "user",
  "password": "User123$"
}

### Login as "Zarządzanie Items - administracja"
POST {{apiUrl}}/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Admin123$"
}

### Get items
GET {{apiUrl}}/items?page=21&pageSize=37
Authorization: Bearer {{bearerToken}}

### Get item by code
GET {{apiUrl}}/items/{{code}}
Authorization: Bearer {{bearerToken}}

### Create item
POST {{apiUrl}}/items
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "code": "{{code}}",
  "name": "Test name",
  "color": "red",
  "notes": "Lorem ipsum dolor sit amet."
}

### Update item
PUT {{apiUrl}}/items
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "code": "{{code}}",
  "name": "Test name updated",
  "color": "green",
  "notes": "Lorem ipsum dolor sit amet updated."
}