@apiUrl = https://localhost/api
@bearerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImp0aSI6IjU4NDNmYjdjLWE3NzEtNDFmMi04NzlhLTY5MzJhMTFlOWMwNyIsImVtYWlsIjoiYWRtaW4iLCJpZCI6IjVjZDcwMjBhLTI4OGUtNDQ5YS05NDQ0LTcwMjY3MmJlZDI0NSIsInJvbGUiOiJJdGVtc0FkbWluIiwibmJmIjoxNjc1ODA4MDg3LCJleHAiOjE2NzY0MTI4ODcsImlhdCI6MTY3NTgwODA4N30.ypqp3IWg2qiKyTbJRu_pXP6HlI85OBLb-ksb55q6Lls
@code = test

### Health check
GET {{apiUrl}}/healthcheck

### Login as "Administracja Items"
POST {{apiUrl}}/login
Content-Type: application/json

{
  "username": "user",
  "password": "User123$"
}

### Login as "Zarządzanie Items - administracja"
POST {{apiUrl}}/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Admin123$"
}

### Get items
GET {{apiUrl}}/items
Authorization: Bearer {{bearerToken}}

### Get item by code
GET {{apiUrl}}/items/{{code}}
Authorization: Bearer {{bearerToken}}

### Create item
POST {{apiUrl}}/items
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "code": "{{code}}",
  "name": "Test name",
  "color": "red",
  "notes": "Lorem ipsum dolor sit amet."
}

### Update item
PUT {{apiUrl}}/items
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "code": "{{code}}",
  "name": "Test name updated",
  "color": "green",
  "notes": "Lorem ipsum dolor sit amet updated."
}