@apiUrl = https://localhost/api
@bearerToken = test
@code = test

### Health check
GET {{apiUrl}}/healthcheck

### Login as "Administracja Items"
POST {{apiUrl}}/login
Content-Type: application/json

{
  "username": "user",
  "password": "user123$"
}

### Login as "Zarządzanie Items - administracja"
POST {{apiUrl}}/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123$"
}

### Get items
GET {{apiUrl}}/items
Authorization: Bearer {{bearerToken}}

### Get item by code
GET {{apiUrl}}/items/{{code}}
Authorization: Bearer {{bearerToken}}

### Create item
POST {{apiUrl}}/items
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "code": "{{code}}",
  "name": "Test name",
  "color": "red",
  "notes": "Lorem ipsum dolor sit amet."
}

### Update item
PUT {{apiUrl}}/items
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "code": "{{code}}",
  "name": "Test name updated",
  "color": "green",
  "notes": "Lorem ipsum dolor sit amet updated."
}